### ISSUE TITLE
Intermittent network issue

### ISSUE THREAD

**Issue by kencjones** [artyom-tarasenko/openfirmware#2]
testing using the tap interface ping and tcp traffic is very intermittent. Can sometimes get to a telnet passord prompt. It could be related to timeout values. testing from subnet that is only from guest to tap interface. All setting set with static address's.

**Comment by artyom-tarasenko** [comment]
can also confirm it with the user mode networking:
```
# ping 10.0.2.2
PING 10.0.2.2: (10.0.2.2): 56 data bytes
64 bytes from 10.0.2.2: icmp_seq=0 ttl=255 time=2728 ms
64 bytes from 10.0.2.2: icmp_seq=1 ttl=255 time=1839 ms
64 bytes from 10.0.2.2: icmp_seq=2 ttl=255 time=968 ms
^C
----10.0.2.2 PING Statistics----
17 packets transmitted, 3 packets received, 82% packet loss
round-trip min/avg/max = 968/1845/2728 ms
```
Will look into it.

**Comment by artyom-tarasenko** [comment]
Fixed in today's pre-release
